#!/bin/sh -ex

# RightScript: Debootstrap configure fstab
#
# Description: Configures the /etc/fstab within the debootstrap target directory (as well as the mib-ebs-root)
#
# Author: Chris Fordham <chris.fordham@rightscale.com>

# Copyright (c) 2007-2008 by RightScale Inc., all rights reserved worldwide

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

: ${DEBIAN_IMAGE_ROOT_FSTYPE:=ext4}

# Debootstrap local configurations
DEBOOTSTRAP_TARGET_DIR=`eval echo $DEBOOTSTRAP_TARGET_DIR`		# evaluate the input (commands such as date can be injected)

root_fstype="$DEBIAN_IMAGE_ROOT_FSTYPE"

#
#  Configure fstab (master chroot)
#
cat <<EOF>"$DEBOOTSTRAP_TARGET_DIR"/etc/fstab
# /etc/fstab: static file system information.
#
# See fstab(5).
#
# fstab generated by Debian Machine Image Builder, RightScale Inc.
#
# <file system>         <mount point>           <type>  <options>               <dump>  <pass>
/dev/xvda1              /                       $root_fstype    defaults                1       2
none                    /proc                   proc    defaults,noauto         0       0
none                    /dev/pts                devpts  gid=5,mode=620,noauto   0       0
none                    /dev/shm                tmpfs   defaults                0       0
none                    /sys                    sysfs   defaults,noauto         0       0

EOF

echo 'fstab contents:'
cat "$DEBOOTSTRAP_TARGET_DIR"/etc/fstab

echo 'Done.'