#!/bin/bash -e

# RightScript: Centosbootstrap: configure fstab for EBS AMI
#
# Description: Configures the fstab on the mounted EBS volume.
#
# Author: Chris Fordham <chris.fordham@rightscale.com>

# Copyright (c) 2007-2008 by RightScale Inc., all rights reserved worldwide

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

: ${MIB_EBS_IMAGE_ROOT_FSTYPE:=ext4}

root_fstype="$MIB_EBS_IMAGE_ROOT_FSTYPE"

#
#  Configure fstab (for EBS AMI)
#
cat <<EOF>/mnt/mib-ebs-root/etc/fstab
# /etc/fstab: static file system information.
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
# fstab generated by CentOS Machine Image Builder, RightScale Inc.
#
# <file system>         <mount point>           <type>  <options>               <dump>  <pass>
/dev/xvda1              /mnt/boot               ext2    errors=remount-ro       0       1
/dev/xvda2              /                       $root_fstype    defaults                1       2
/dev/xvda3              none                    swap    sw                      0       0
tmpfs                   /dev/shm                tmpfs   defaults        0 0
devpts                  /dev/pts                devpts  gid=5,mode=620  0 0
sysfs                   /sys                    sysfs   defaults        0 0
proc                    /proc                   proc    defaults        0 0

EOF

echo 'Done.'