#!/bin/sh -ex

# RightScript: Centosbootstrap: configure fstab
#
# Description: Configures the /etc/fstab within the Centosbootstrap target directory.
#
# Author: Chris Fordham <chris.fordham@rightscale.com>

# Copyright (c) 2007-2008 by RightScale Inc., all rights reserved worldwide

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Centosbootstrap local configurations
CENTOSBOOTSTRAP_CHROOT=`eval echo $CENTOSBOOTSTRAP_CHROOT`		# evaluate the input (commands such as date can be injected)
: ${CENTOS_IMAGE_ROOT_FSTYPE:=ext4}
root_fstype="$CENTOS_IMAGE_ROOT_FSTYPE"

#
#  Configure fstab (for master image/instance-store AMI)
#
cat <<EOF>"$CENTOSBOOTSTRAP_CHROOT/etc/fstab"
# /etc/fstab: static file system information.
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
# fstab generated by CentOS Machine Image Builder, RightScale Inc.
#
# <file system>         <mount point>           <type>  <options>               <dump>  <pass>
/dev/xvda1              /                       $root_fstype    defaults                1       2
tmpfs                   /dev/shm                tmpfs   defaults        0 0
devpts                  /dev/pts                devpts  gid=5,mode=620  0 0
sysfs                   /sys                    sysfs   defaults        0 0
proc                    /proc                   proc    defaults        0 0

EOF

echo 'fstab contents:'
cat "$CENTOSBOOTSTRAP_CHROOT/etc/fstab"

echo 'Done.'